# Generated by Django 4.1.7 on 2023-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Daily_shop_App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
