# Generated by Django 4.1.7 on 2023-04-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Daily_shop_App", "0007_cart_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="net_price", field=models.IntegerField(default=0),
        ),
    ]
