# Generated by Django 4.1.7 on 2023-04-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Daily_shop_App",
            "0009_cart_razorpay_order_id_cart_razorpay_payment_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "razorpay_payment_signature",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RemoveField(model_name="cart", name="razorpay_order_id",),
        migrations.RemoveField(model_name="cart", name="razorpay_payment_id",),
        migrations.RemoveField(model_name="cart", name="razorpay_payment_signature",),
    ]
